// Code generated by Kitex v0.16.1. DO NOT EDIT.

package groupcache

import (
	"context"
	geecache "geecache/kitex_gen/geecache"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Get(ctx context.Context, req *geecache.Request, callOptions ...callopt.Option) (r *geecache.Response, err error)
	Set(ctx context.Context, req *geecache.SetRequest, callOptions ...callopt.Option) (r *geecache.SetResponse, err error)
	Delete(ctx context.Context, req *geecache.DeleteRequest, callOptions ...callopt.Option) (r *geecache.DeleteResponse, err error)
	Clear(ctx context.Context, req *geecache.ClearRequest, callOptions ...callopt.Option) (r *geecache.ClearResponse, err error)
	Stats(ctx context.Context, req *geecache.StatsRequest, callOptions ...callopt.Option) (r *geecache.StatsResponse, err error)
	GetMulti(ctx context.Context, req *geecache.GetMultiRequest, callOptions ...callopt.Option) (r *geecache.GetMultiResponse, err error)
	SetMulti(ctx context.Context, req *geecache.SetMultiRequest, callOptions ...callopt.Option) (r *geecache.SetMultiResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kGroupCacheClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kGroupCacheClient struct {
	*kClient
}

func (p *kGroupCacheClient) Get(ctx context.Context, req *geecache.Request, callOptions ...callopt.Option) (r *geecache.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Get(ctx, req)
}

func (p *kGroupCacheClient) Set(ctx context.Context, req *geecache.SetRequest, callOptions ...callopt.Option) (r *geecache.SetResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Set(ctx, req)
}

func (p *kGroupCacheClient) Delete(ctx context.Context, req *geecache.DeleteRequest, callOptions ...callopt.Option) (r *geecache.DeleteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, req)
}

func (p *kGroupCacheClient) Clear(ctx context.Context, req *geecache.ClearRequest, callOptions ...callopt.Option) (r *geecache.ClearResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Clear(ctx, req)
}

func (p *kGroupCacheClient) Stats(ctx context.Context, req *geecache.StatsRequest, callOptions ...callopt.Option) (r *geecache.StatsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Stats(ctx, req)
}

func (p *kGroupCacheClient) GetMulti(ctx context.Context, req *geecache.GetMultiRequest, callOptions ...callopt.Option) (r *geecache.GetMultiResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMulti(ctx, req)
}

func (p *kGroupCacheClient) SetMulti(ctx context.Context, req *geecache.SetMultiRequest, callOptions ...callopt.Option) (r *geecache.SetMultiResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetMulti(ctx, req)
}
