// Code generated by Kitex v0.16.1. DO NOT EDIT.

package groupcache

import (
	"context"
	"errors"
	geecache "mygocache/kitex_gen/geecache"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Get": kitex.NewMethodInfo(
		getHandler,
		newGroupCacheGetArgs,
		newGroupCacheGetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Set": kitex.NewMethodInfo(
		setHandler,
		newGroupCacheSetArgs,
		newGroupCacheSetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Delete": kitex.NewMethodInfo(
		deleteHandler,
		newGroupCacheDeleteArgs,
		newGroupCacheDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Clear": kitex.NewMethodInfo(
		clearHandler,
		newGroupCacheClearArgs,
		newGroupCacheClearResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Stats": kitex.NewMethodInfo(
		statsHandler,
		newGroupCacheStatsArgs,
		newGroupCacheStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMulti": kitex.NewMethodInfo(
		getMultiHandler,
		newGroupCacheGetMultiArgs,
		newGroupCacheGetMultiResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetMulti": kitex.NewMethodInfo(
		setMultiHandler,
		newGroupCacheSetMultiArgs,
		newGroupCacheSetMultiResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	groupCacheServiceInfo                = NewServiceInfo()
	groupCacheServiceInfoForClient       = NewServiceInfoForClient()
	groupCacheServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return groupCacheServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return groupCacheServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return groupCacheServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "GroupCache"
	handlerType := (*geecache.GroupCache)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "geecache",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*geecache.GroupCacheGetArgs)
	realResult := result.(*geecache.GroupCacheGetResult)
	success, err := handler.(geecache.GroupCache).Get(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupCacheGetArgs() interface{} {
	return geecache.NewGroupCacheGetArgs()
}

func newGroupCacheGetResult() interface{} {
	return geecache.NewGroupCacheGetResult()
}

func setHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*geecache.GroupCacheSetArgs)
	realResult := result.(*geecache.GroupCacheSetResult)
	success, err := handler.(geecache.GroupCache).Set(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupCacheSetArgs() interface{} {
	return geecache.NewGroupCacheSetArgs()
}

func newGroupCacheSetResult() interface{} {
	return geecache.NewGroupCacheSetResult()
}

func deleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*geecache.GroupCacheDeleteArgs)
	realResult := result.(*geecache.GroupCacheDeleteResult)
	success, err := handler.(geecache.GroupCache).Delete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupCacheDeleteArgs() interface{} {
	return geecache.NewGroupCacheDeleteArgs()
}

func newGroupCacheDeleteResult() interface{} {
	return geecache.NewGroupCacheDeleteResult()
}

func clearHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*geecache.GroupCacheClearArgs)
	realResult := result.(*geecache.GroupCacheClearResult)
	success, err := handler.(geecache.GroupCache).Clear(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupCacheClearArgs() interface{} {
	return geecache.NewGroupCacheClearArgs()
}

func newGroupCacheClearResult() interface{} {
	return geecache.NewGroupCacheClearResult()
}

func statsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*geecache.GroupCacheStatsArgs)
	realResult := result.(*geecache.GroupCacheStatsResult)
	success, err := handler.(geecache.GroupCache).Stats(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupCacheStatsArgs() interface{} {
	return geecache.NewGroupCacheStatsArgs()
}

func newGroupCacheStatsResult() interface{} {
	return geecache.NewGroupCacheStatsResult()
}

func getMultiHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*geecache.GroupCacheGetMultiArgs)
	realResult := result.(*geecache.GroupCacheGetMultiResult)
	success, err := handler.(geecache.GroupCache).GetMulti(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupCacheGetMultiArgs() interface{} {
	return geecache.NewGroupCacheGetMultiArgs()
}

func newGroupCacheGetMultiResult() interface{} {
	return geecache.NewGroupCacheGetMultiResult()
}

func setMultiHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*geecache.GroupCacheSetMultiArgs)
	realResult := result.(*geecache.GroupCacheSetMultiResult)
	success, err := handler.(geecache.GroupCache).SetMulti(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupCacheSetMultiArgs() interface{} {
	return geecache.NewGroupCacheSetMultiArgs()
}

func newGroupCacheSetMultiResult() interface{} {
	return geecache.NewGroupCacheSetMultiResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Get(ctx context.Context, req *geecache.Request) (r *geecache.Response, err error) {
	var _args geecache.GroupCacheGetArgs
	_args.Req = req
	var _result geecache.GroupCacheGetResult
	if err = p.c.Call(ctx, "Get", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Set(ctx context.Context, req *geecache.SetRequest) (r *geecache.SetResponse, err error) {
	var _args geecache.GroupCacheSetArgs
	_args.Req = req
	var _result geecache.GroupCacheSetResult
	if err = p.c.Call(ctx, "Set", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Delete(ctx context.Context, req *geecache.DeleteRequest) (r *geecache.DeleteResponse, err error) {
	var _args geecache.GroupCacheDeleteArgs
	_args.Req = req
	var _result geecache.GroupCacheDeleteResult
	if err = p.c.Call(ctx, "Delete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Clear(ctx context.Context, req *geecache.ClearRequest) (r *geecache.ClearResponse, err error) {
	var _args geecache.GroupCacheClearArgs
	_args.Req = req
	var _result geecache.GroupCacheClearResult
	if err = p.c.Call(ctx, "Clear", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Stats(ctx context.Context, req *geecache.StatsRequest) (r *geecache.StatsResponse, err error) {
	var _args geecache.GroupCacheStatsArgs
	_args.Req = req
	var _result geecache.GroupCacheStatsResult
	if err = p.c.Call(ctx, "Stats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMulti(ctx context.Context, req *geecache.GetMultiRequest) (r *geecache.GetMultiResponse, err error) {
	var _args geecache.GroupCacheGetMultiArgs
	_args.Req = req
	var _result geecache.GroupCacheGetMultiResult
	if err = p.c.Call(ctx, "GetMulti", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetMulti(ctx context.Context, req *geecache.SetMultiRequest) (r *geecache.SetMultiResponse, err error) {
	var _args geecache.GroupCacheSetMultiArgs
	_args.Req = req
	var _result geecache.GroupCacheSetMultiResult
	if err = p.c.Call(ctx, "SetMulti", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
