// Code generated by Kitex v0.16.1. DO NOT EDIT.

package groupcache

import (
	"context"
	"errors"
	geecache "geecache/kitex_gen/geecache"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Get": kitex.NewMethodInfo(
		getHandler,
		newGroupCacheGetArgs,
		newGroupCacheGetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	groupCacheServiceInfo                = NewServiceInfo()
	groupCacheServiceInfoForClient       = NewServiceInfoForClient()
	groupCacheServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return groupCacheServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return groupCacheServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return groupCacheServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "GroupCache"
	handlerType := (*geecache.GroupCache)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "geecache",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*geecache.GroupCacheGetArgs)
	realResult := result.(*geecache.GroupCacheGetResult)
	success, err := handler.(geecache.GroupCache).Get(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupCacheGetArgs() interface{} {
	return geecache.NewGroupCacheGetArgs()
}

func newGroupCacheGetResult() interface{} {
	return geecache.NewGroupCacheGetResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Get(ctx context.Context, req *geecache.Request) (r *geecache.Response, err error) {
	var _args geecache.GroupCacheGetArgs
	_args.Req = req
	var _result geecache.GroupCacheGetResult
	if err = p.c.Call(ctx, "Get", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
