// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package geecache

import (
	"context"
	"fmt"
)

type Request struct {
	Group string `thrift:"group,1" frugal:"1,default,string" json:"group"`
	Key   string `thrift:"key,2" frugal:"2,default,string" json:"key"`
}

func NewRequest() *Request {
	return &Request{}
}

func (p *Request) InitDefault() {
}

func (p *Request) GetGroup() (v string) {
	return p.Group
}

func (p *Request) GetKey() (v string) {
	return p.Key
}
func (p *Request) SetGroup(val string) {
	p.Group = val
}
func (p *Request) SetKey(val string) {
	p.Key = val
}

func (p *Request) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Request(%+v)", *p)
}

var fieldIDToName_Request = map[int16]string{
	1: "group",
	2: "key",
}

type Response struct {
	Value []byte `thrift:"value,1" frugal:"1,default,binary" json:"value"`
}

func NewResponse() *Response {
	return &Response{}
}

func (p *Response) InitDefault() {
}

func (p *Response) GetValue() (v []byte) {
	return p.Value
}
func (p *Response) SetValue(val []byte) {
	p.Value = val
}

func (p *Response) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Response(%+v)", *p)
}

var fieldIDToName_Response = map[int16]string{
	1: "value",
}

type SetRequest struct {
	Group string `thrift:"group,1" frugal:"1,default,string" json:"group"`
	Key   string `thrift:"key,2" frugal:"2,default,string" json:"key"`
	Value []byte `thrift:"value,3" frugal:"3,default,binary" json:"value"`
	Ttl   int64  `thrift:"ttl,4" frugal:"4,default,i64" json:"ttl"`
}

func NewSetRequest() *SetRequest {
	return &SetRequest{}
}

func (p *SetRequest) InitDefault() {
}

func (p *SetRequest) GetGroup() (v string) {
	return p.Group
}

func (p *SetRequest) GetKey() (v string) {
	return p.Key
}

func (p *SetRequest) GetValue() (v []byte) {
	return p.Value
}

func (p *SetRequest) GetTtl() (v int64) {
	return p.Ttl
}
func (p *SetRequest) SetGroup(val string) {
	p.Group = val
}
func (p *SetRequest) SetKey(val string) {
	p.Key = val
}
func (p *SetRequest) SetValue(val []byte) {
	p.Value = val
}
func (p *SetRequest) SetTtl(val int64) {
	p.Ttl = val
}

func (p *SetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetRequest(%+v)", *p)
}

var fieldIDToName_SetRequest = map[int16]string{
	1: "group",
	2: "key",
	3: "value",
	4: "ttl",
}

type SetResponse struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewSetResponse() *SetResponse {
	return &SetResponse{}
}

func (p *SetResponse) InitDefault() {
}

func (p *SetResponse) GetSuccess() (v bool) {
	return p.Success
}
func (p *SetResponse) SetSuccess(val bool) {
	p.Success = val
}

func (p *SetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetResponse(%+v)", *p)
}

var fieldIDToName_SetResponse = map[int16]string{
	1: "success",
}

type DeleteRequest struct {
	Group string `thrift:"group,1" frugal:"1,default,string" json:"group"`
	Key   string `thrift:"key,2" frugal:"2,default,string" json:"key"`
}

func NewDeleteRequest() *DeleteRequest {
	return &DeleteRequest{}
}

func (p *DeleteRequest) InitDefault() {
}

func (p *DeleteRequest) GetGroup() (v string) {
	return p.Group
}

func (p *DeleteRequest) GetKey() (v string) {
	return p.Key
}
func (p *DeleteRequest) SetGroup(val string) {
	p.Group = val
}
func (p *DeleteRequest) SetKey(val string) {
	p.Key = val
}

func (p *DeleteRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteRequest(%+v)", *p)
}

var fieldIDToName_DeleteRequest = map[int16]string{
	1: "group",
	2: "key",
}

type DeleteResponse struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewDeleteResponse() *DeleteResponse {
	return &DeleteResponse{}
}

func (p *DeleteResponse) InitDefault() {
}

func (p *DeleteResponse) GetSuccess() (v bool) {
	return p.Success
}
func (p *DeleteResponse) SetSuccess(val bool) {
	p.Success = val
}

func (p *DeleteResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteResponse(%+v)", *p)
}

var fieldIDToName_DeleteResponse = map[int16]string{
	1: "success",
}

type ClearRequest struct {
	Group string `thrift:"group,1" frugal:"1,default,string" json:"group"`
}

func NewClearRequest() *ClearRequest {
	return &ClearRequest{}
}

func (p *ClearRequest) InitDefault() {
}

func (p *ClearRequest) GetGroup() (v string) {
	return p.Group
}
func (p *ClearRequest) SetGroup(val string) {
	p.Group = val
}

func (p *ClearRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClearRequest(%+v)", *p)
}

var fieldIDToName_ClearRequest = map[int16]string{
	1: "group",
}

type ClearResponse struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewClearResponse() *ClearResponse {
	return &ClearResponse{}
}

func (p *ClearResponse) InitDefault() {
}

func (p *ClearResponse) GetSuccess() (v bool) {
	return p.Success
}
func (p *ClearResponse) SetSuccess(val bool) {
	p.Success = val
}

func (p *ClearResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClearResponse(%+v)", *p)
}

var fieldIDToName_ClearResponse = map[int16]string{
	1: "success",
}

type StatsRequest struct {
	Group string `thrift:"group,1" frugal:"1,default,string" json:"group"`
}

func NewStatsRequest() *StatsRequest {
	return &StatsRequest{}
}

func (p *StatsRequest) InitDefault() {
}

func (p *StatsRequest) GetGroup() (v string) {
	return p.Group
}
func (p *StatsRequest) SetGroup(val string) {
	p.Group = val
}

func (p *StatsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StatsRequest(%+v)", *p)
}

var fieldIDToName_StatsRequest = map[int16]string{
	1: "group",
}

type StatsResponse struct {
	ItemCount  int64 `thrift:"itemCount,1" frugal:"1,default,i64" json:"itemCount"`
	HitCount   int64 `thrift:"hitCount,2" frugal:"2,default,i64" json:"hitCount"`
	MissCount  int64 `thrift:"missCount,3" frugal:"3,default,i64" json:"missCount"`
	TotalCount int64 `thrift:"totalCount,4" frugal:"4,default,i64" json:"totalCount"`
}

func NewStatsResponse() *StatsResponse {
	return &StatsResponse{}
}

func (p *StatsResponse) InitDefault() {
}

func (p *StatsResponse) GetItemCount() (v int64) {
	return p.ItemCount
}

func (p *StatsResponse) GetHitCount() (v int64) {
	return p.HitCount
}

func (p *StatsResponse) GetMissCount() (v int64) {
	return p.MissCount
}

func (p *StatsResponse) GetTotalCount() (v int64) {
	return p.TotalCount
}
func (p *StatsResponse) SetItemCount(val int64) {
	p.ItemCount = val
}
func (p *StatsResponse) SetHitCount(val int64) {
	p.HitCount = val
}
func (p *StatsResponse) SetMissCount(val int64) {
	p.MissCount = val
}
func (p *StatsResponse) SetTotalCount(val int64) {
	p.TotalCount = val
}

func (p *StatsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StatsResponse(%+v)", *p)
}

var fieldIDToName_StatsResponse = map[int16]string{
	1: "itemCount",
	2: "hitCount",
	3: "missCount",
	4: "totalCount",
}

type GetMultiRequest struct {
	Group string   `thrift:"group,1" frugal:"1,default,string" json:"group"`
	Keys  []string `thrift:"keys,2" frugal:"2,default,list<string>" json:"keys"`
}

func NewGetMultiRequest() *GetMultiRequest {
	return &GetMultiRequest{}
}

func (p *GetMultiRequest) InitDefault() {
}

func (p *GetMultiRequest) GetGroup() (v string) {
	return p.Group
}

func (p *GetMultiRequest) GetKeys() (v []string) {
	return p.Keys
}
func (p *GetMultiRequest) SetGroup(val string) {
	p.Group = val
}
func (p *GetMultiRequest) SetKeys(val []string) {
	p.Keys = val
}

func (p *GetMultiRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMultiRequest(%+v)", *p)
}

var fieldIDToName_GetMultiRequest = map[int16]string{
	1: "group",
	2: "keys",
}

type GetMultiResponse struct {
	Values map[string][]byte `thrift:"values,1" frugal:"1,default,map<string:binary>" json:"values"`
}

func NewGetMultiResponse() *GetMultiResponse {
	return &GetMultiResponse{}
}

func (p *GetMultiResponse) InitDefault() {
}

func (p *GetMultiResponse) GetValues() (v map[string][]byte) {
	return p.Values
}
func (p *GetMultiResponse) SetValues(val map[string][]byte) {
	p.Values = val
}

func (p *GetMultiResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMultiResponse(%+v)", *p)
}

var fieldIDToName_GetMultiResponse = map[int16]string{
	1: "values",
}

type SetMultiRequest struct {
	Group  string            `thrift:"group,1" frugal:"1,default,string" json:"group"`
	Values map[string][]byte `thrift:"values,2" frugal:"2,default,map<string:binary>" json:"values"`
	Ttl    int64             `thrift:"ttl,3" frugal:"3,default,i64" json:"ttl"`
}

func NewSetMultiRequest() *SetMultiRequest {
	return &SetMultiRequest{}
}

func (p *SetMultiRequest) InitDefault() {
}

func (p *SetMultiRequest) GetGroup() (v string) {
	return p.Group
}

func (p *SetMultiRequest) GetValues() (v map[string][]byte) {
	return p.Values
}

func (p *SetMultiRequest) GetTtl() (v int64) {
	return p.Ttl
}
func (p *SetMultiRequest) SetGroup(val string) {
	p.Group = val
}
func (p *SetMultiRequest) SetValues(val map[string][]byte) {
	p.Values = val
}
func (p *SetMultiRequest) SetTtl(val int64) {
	p.Ttl = val
}

func (p *SetMultiRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetMultiRequest(%+v)", *p)
}

var fieldIDToName_SetMultiRequest = map[int16]string{
	1: "group",
	2: "values",
	3: "ttl",
}

type SetMultiResponse struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewSetMultiResponse() *SetMultiResponse {
	return &SetMultiResponse{}
}

func (p *SetMultiResponse) InitDefault() {
}

func (p *SetMultiResponse) GetSuccess() (v bool) {
	return p.Success
}
func (p *SetMultiResponse) SetSuccess(val bool) {
	p.Success = val
}

func (p *SetMultiResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetMultiResponse(%+v)", *p)
}

var fieldIDToName_SetMultiResponse = map[int16]string{
	1: "success",
}

type GroupCache interface {
	Get(ctx context.Context, req *Request) (r *Response, err error)

	Set(ctx context.Context, req *SetRequest) (r *SetResponse, err error)

	Delete(ctx context.Context, req *DeleteRequest) (r *DeleteResponse, err error)

	Clear(ctx context.Context, req *ClearRequest) (r *ClearResponse, err error)

	Stats(ctx context.Context, req *StatsRequest) (r *StatsResponse, err error)

	GetMulti(ctx context.Context, req *GetMultiRequest) (r *GetMultiResponse, err error)

	SetMulti(ctx context.Context, req *SetMultiRequest) (r *SetMultiResponse, err error)
}

type GroupCacheGetArgs struct {
	Req *Request `thrift:"req,1" frugal:"1,default,Request" json:"req"`
}

func NewGroupCacheGetArgs() *GroupCacheGetArgs {
	return &GroupCacheGetArgs{}
}

func (p *GroupCacheGetArgs) InitDefault() {
}

var GroupCacheGetArgs_Req_DEFAULT *Request

func (p *GroupCacheGetArgs) GetReq() (v *Request) {
	if !p.IsSetReq() {
		return GroupCacheGetArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupCacheGetArgs) SetReq(val *Request) {
	p.Req = val
}

func (p *GroupCacheGetArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupCacheGetArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheGetArgs(%+v)", *p)
}

var fieldIDToName_GroupCacheGetArgs = map[int16]string{
	1: "req",
}

type GroupCacheGetResult struct {
	Success *Response `thrift:"success,0,optional" frugal:"0,optional,Response" json:"success,omitempty"`
}

func NewGroupCacheGetResult() *GroupCacheGetResult {
	return &GroupCacheGetResult{}
}

func (p *GroupCacheGetResult) InitDefault() {
}

var GroupCacheGetResult_Success_DEFAULT *Response

func (p *GroupCacheGetResult) GetSuccess() (v *Response) {
	if !p.IsSetSuccess() {
		return GroupCacheGetResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupCacheGetResult) SetSuccess(x interface{}) {
	p.Success = x.(*Response)
}

func (p *GroupCacheGetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupCacheGetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheGetResult(%+v)", *p)
}

var fieldIDToName_GroupCacheGetResult = map[int16]string{
	0: "success",
}

type GroupCacheSetArgs struct {
	Req *SetRequest `thrift:"req,1" frugal:"1,default,SetRequest" json:"req"`
}

func NewGroupCacheSetArgs() *GroupCacheSetArgs {
	return &GroupCacheSetArgs{}
}

func (p *GroupCacheSetArgs) InitDefault() {
}

var GroupCacheSetArgs_Req_DEFAULT *SetRequest

func (p *GroupCacheSetArgs) GetReq() (v *SetRequest) {
	if !p.IsSetReq() {
		return GroupCacheSetArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupCacheSetArgs) SetReq(val *SetRequest) {
	p.Req = val
}

func (p *GroupCacheSetArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupCacheSetArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheSetArgs(%+v)", *p)
}

var fieldIDToName_GroupCacheSetArgs = map[int16]string{
	1: "req",
}

type GroupCacheSetResult struct {
	Success *SetResponse `thrift:"success,0,optional" frugal:"0,optional,SetResponse" json:"success,omitempty"`
}

func NewGroupCacheSetResult() *GroupCacheSetResult {
	return &GroupCacheSetResult{}
}

func (p *GroupCacheSetResult) InitDefault() {
}

var GroupCacheSetResult_Success_DEFAULT *SetResponse

func (p *GroupCacheSetResult) GetSuccess() (v *SetResponse) {
	if !p.IsSetSuccess() {
		return GroupCacheSetResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupCacheSetResult) SetSuccess(x interface{}) {
	p.Success = x.(*SetResponse)
}

func (p *GroupCacheSetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupCacheSetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheSetResult(%+v)", *p)
}

var fieldIDToName_GroupCacheSetResult = map[int16]string{
	0: "success",
}

type GroupCacheDeleteArgs struct {
	Req *DeleteRequest `thrift:"req,1" frugal:"1,default,DeleteRequest" json:"req"`
}

func NewGroupCacheDeleteArgs() *GroupCacheDeleteArgs {
	return &GroupCacheDeleteArgs{}
}

func (p *GroupCacheDeleteArgs) InitDefault() {
}

var GroupCacheDeleteArgs_Req_DEFAULT *DeleteRequest

func (p *GroupCacheDeleteArgs) GetReq() (v *DeleteRequest) {
	if !p.IsSetReq() {
		return GroupCacheDeleteArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupCacheDeleteArgs) SetReq(val *DeleteRequest) {
	p.Req = val
}

func (p *GroupCacheDeleteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupCacheDeleteArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheDeleteArgs(%+v)", *p)
}

var fieldIDToName_GroupCacheDeleteArgs = map[int16]string{
	1: "req",
}

type GroupCacheDeleteResult struct {
	Success *DeleteResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteResponse" json:"success,omitempty"`
}

func NewGroupCacheDeleteResult() *GroupCacheDeleteResult {
	return &GroupCacheDeleteResult{}
}

func (p *GroupCacheDeleteResult) InitDefault() {
}

var GroupCacheDeleteResult_Success_DEFAULT *DeleteResponse

func (p *GroupCacheDeleteResult) GetSuccess() (v *DeleteResponse) {
	if !p.IsSetSuccess() {
		return GroupCacheDeleteResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupCacheDeleteResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteResponse)
}

func (p *GroupCacheDeleteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupCacheDeleteResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheDeleteResult(%+v)", *p)
}

var fieldIDToName_GroupCacheDeleteResult = map[int16]string{
	0: "success",
}

type GroupCacheClearArgs struct {
	Req *ClearRequest `thrift:"req,1" frugal:"1,default,ClearRequest" json:"req"`
}

func NewGroupCacheClearArgs() *GroupCacheClearArgs {
	return &GroupCacheClearArgs{}
}

func (p *GroupCacheClearArgs) InitDefault() {
}

var GroupCacheClearArgs_Req_DEFAULT *ClearRequest

func (p *GroupCacheClearArgs) GetReq() (v *ClearRequest) {
	if !p.IsSetReq() {
		return GroupCacheClearArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupCacheClearArgs) SetReq(val *ClearRequest) {
	p.Req = val
}

func (p *GroupCacheClearArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupCacheClearArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheClearArgs(%+v)", *p)
}

var fieldIDToName_GroupCacheClearArgs = map[int16]string{
	1: "req",
}

type GroupCacheClearResult struct {
	Success *ClearResponse `thrift:"success,0,optional" frugal:"0,optional,ClearResponse" json:"success,omitempty"`
}

func NewGroupCacheClearResult() *GroupCacheClearResult {
	return &GroupCacheClearResult{}
}

func (p *GroupCacheClearResult) InitDefault() {
}

var GroupCacheClearResult_Success_DEFAULT *ClearResponse

func (p *GroupCacheClearResult) GetSuccess() (v *ClearResponse) {
	if !p.IsSetSuccess() {
		return GroupCacheClearResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupCacheClearResult) SetSuccess(x interface{}) {
	p.Success = x.(*ClearResponse)
}

func (p *GroupCacheClearResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupCacheClearResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheClearResult(%+v)", *p)
}

var fieldIDToName_GroupCacheClearResult = map[int16]string{
	0: "success",
}

type GroupCacheStatsArgs struct {
	Req *StatsRequest `thrift:"req,1" frugal:"1,default,StatsRequest" json:"req"`
}

func NewGroupCacheStatsArgs() *GroupCacheStatsArgs {
	return &GroupCacheStatsArgs{}
}

func (p *GroupCacheStatsArgs) InitDefault() {
}

var GroupCacheStatsArgs_Req_DEFAULT *StatsRequest

func (p *GroupCacheStatsArgs) GetReq() (v *StatsRequest) {
	if !p.IsSetReq() {
		return GroupCacheStatsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupCacheStatsArgs) SetReq(val *StatsRequest) {
	p.Req = val
}

func (p *GroupCacheStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupCacheStatsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheStatsArgs(%+v)", *p)
}

var fieldIDToName_GroupCacheStatsArgs = map[int16]string{
	1: "req",
}

type GroupCacheStatsResult struct {
	Success *StatsResponse `thrift:"success,0,optional" frugal:"0,optional,StatsResponse" json:"success,omitempty"`
}

func NewGroupCacheStatsResult() *GroupCacheStatsResult {
	return &GroupCacheStatsResult{}
}

func (p *GroupCacheStatsResult) InitDefault() {
}

var GroupCacheStatsResult_Success_DEFAULT *StatsResponse

func (p *GroupCacheStatsResult) GetSuccess() (v *StatsResponse) {
	if !p.IsSetSuccess() {
		return GroupCacheStatsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupCacheStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*StatsResponse)
}

func (p *GroupCacheStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupCacheStatsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheStatsResult(%+v)", *p)
}

var fieldIDToName_GroupCacheStatsResult = map[int16]string{
	0: "success",
}

type GroupCacheGetMultiArgs struct {
	Req *GetMultiRequest `thrift:"req,1" frugal:"1,default,GetMultiRequest" json:"req"`
}

func NewGroupCacheGetMultiArgs() *GroupCacheGetMultiArgs {
	return &GroupCacheGetMultiArgs{}
}

func (p *GroupCacheGetMultiArgs) InitDefault() {
}

var GroupCacheGetMultiArgs_Req_DEFAULT *GetMultiRequest

func (p *GroupCacheGetMultiArgs) GetReq() (v *GetMultiRequest) {
	if !p.IsSetReq() {
		return GroupCacheGetMultiArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupCacheGetMultiArgs) SetReq(val *GetMultiRequest) {
	p.Req = val
}

func (p *GroupCacheGetMultiArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupCacheGetMultiArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheGetMultiArgs(%+v)", *p)
}

var fieldIDToName_GroupCacheGetMultiArgs = map[int16]string{
	1: "req",
}

type GroupCacheGetMultiResult struct {
	Success *GetMultiResponse `thrift:"success,0,optional" frugal:"0,optional,GetMultiResponse" json:"success,omitempty"`
}

func NewGroupCacheGetMultiResult() *GroupCacheGetMultiResult {
	return &GroupCacheGetMultiResult{}
}

func (p *GroupCacheGetMultiResult) InitDefault() {
}

var GroupCacheGetMultiResult_Success_DEFAULT *GetMultiResponse

func (p *GroupCacheGetMultiResult) GetSuccess() (v *GetMultiResponse) {
	if !p.IsSetSuccess() {
		return GroupCacheGetMultiResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupCacheGetMultiResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetMultiResponse)
}

func (p *GroupCacheGetMultiResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupCacheGetMultiResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheGetMultiResult(%+v)", *p)
}

var fieldIDToName_GroupCacheGetMultiResult = map[int16]string{
	0: "success",
}

type GroupCacheSetMultiArgs struct {
	Req *SetMultiRequest `thrift:"req,1" frugal:"1,default,SetMultiRequest" json:"req"`
}

func NewGroupCacheSetMultiArgs() *GroupCacheSetMultiArgs {
	return &GroupCacheSetMultiArgs{}
}

func (p *GroupCacheSetMultiArgs) InitDefault() {
}

var GroupCacheSetMultiArgs_Req_DEFAULT *SetMultiRequest

func (p *GroupCacheSetMultiArgs) GetReq() (v *SetMultiRequest) {
	if !p.IsSetReq() {
		return GroupCacheSetMultiArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupCacheSetMultiArgs) SetReq(val *SetMultiRequest) {
	p.Req = val
}

func (p *GroupCacheSetMultiArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupCacheSetMultiArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheSetMultiArgs(%+v)", *p)
}

var fieldIDToName_GroupCacheSetMultiArgs = map[int16]string{
	1: "req",
}

type GroupCacheSetMultiResult struct {
	Success *SetMultiResponse `thrift:"success,0,optional" frugal:"0,optional,SetMultiResponse" json:"success,omitempty"`
}

func NewGroupCacheSetMultiResult() *GroupCacheSetMultiResult {
	return &GroupCacheSetMultiResult{}
}

func (p *GroupCacheSetMultiResult) InitDefault() {
}

var GroupCacheSetMultiResult_Success_DEFAULT *SetMultiResponse

func (p *GroupCacheSetMultiResult) GetSuccess() (v *SetMultiResponse) {
	if !p.IsSetSuccess() {
		return GroupCacheSetMultiResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupCacheSetMultiResult) SetSuccess(x interface{}) {
	p.Success = x.(*SetMultiResponse)
}

func (p *GroupCacheSetMultiResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupCacheSetMultiResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheSetMultiResult(%+v)", *p)
}

var fieldIDToName_GroupCacheSetMultiResult = map[int16]string{
	0: "success",
}
