// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package geecache

import (
	"context"
	"fmt"
)

type Request struct {
	Group string `thrift:"group,1" frugal:"1,default,string" json:"group"`
	Key   string `thrift:"key,2" frugal:"2,default,string" json:"key"`
}

func NewRequest() *Request {
	return &Request{}
}

func (p *Request) InitDefault() {
}

func (p *Request) GetGroup() (v string) {
	return p.Group
}

func (p *Request) GetKey() (v string) {
	return p.Key
}
func (p *Request) SetGroup(val string) {
	p.Group = val
}
func (p *Request) SetKey(val string) {
	p.Key = val
}

func (p *Request) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Request(%+v)", *p)
}

var fieldIDToName_Request = map[int16]string{
	1: "group",
	2: "key",
}

type Response struct {
	Value []byte `thrift:"value,1" frugal:"1,default,binary" json:"value"`
}

func NewResponse() *Response {
	return &Response{}
}

func (p *Response) InitDefault() {
}

func (p *Response) GetValue() (v []byte) {
	return p.Value
}
func (p *Response) SetValue(val []byte) {
	p.Value = val
}

func (p *Response) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Response(%+v)", *p)
}

var fieldIDToName_Response = map[int16]string{
	1: "value",
}

type GroupCache interface {
	Get(ctx context.Context, req *Request) (r *Response, err error)
}

type GroupCacheGetArgs struct {
	Req *Request `thrift:"req,1" frugal:"1,default,Request" json:"req"`
}

func NewGroupCacheGetArgs() *GroupCacheGetArgs {
	return &GroupCacheGetArgs{}
}

func (p *GroupCacheGetArgs) InitDefault() {
}

var GroupCacheGetArgs_Req_DEFAULT *Request

func (p *GroupCacheGetArgs) GetReq() (v *Request) {
	if !p.IsSetReq() {
		return GroupCacheGetArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupCacheGetArgs) SetReq(val *Request) {
	p.Req = val
}

func (p *GroupCacheGetArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupCacheGetArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheGetArgs(%+v)", *p)
}

var fieldIDToName_GroupCacheGetArgs = map[int16]string{
	1: "req",
}

type GroupCacheGetResult struct {
	Success *Response `thrift:"success,0,optional" frugal:"0,optional,Response" json:"success,omitempty"`
}

func NewGroupCacheGetResult() *GroupCacheGetResult {
	return &GroupCacheGetResult{}
}

func (p *GroupCacheGetResult) InitDefault() {
}

var GroupCacheGetResult_Success_DEFAULT *Response

func (p *GroupCacheGetResult) GetSuccess() (v *Response) {
	if !p.IsSetSuccess() {
		return GroupCacheGetResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupCacheGetResult) SetSuccess(x interface{}) {
	p.Success = x.(*Response)
}

func (p *GroupCacheGetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupCacheGetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCacheGetResult(%+v)", *p)
}

var fieldIDToName_GroupCacheGetResult = map[int16]string{
	0: "success",
}
